from pydantic import BaseModel

class MenuBase(BaseModel):
    # Add any menu-specific fields here if you have them
    pass

class MenuCreate(MenuBase):
    id: int  # Usually autogenerated from items, so maybe Optional[int] = None

class MenuUpdate(MenuBase):
    pass

class Menu(MenuBase):
    id: int

    class Config:
        orm_mode = True

